x_offset:                 -0.010
y_offset:                 0.005
z_offset:                 0.020
roll_offset:              0
pitch_offset:             0
yaw_offset:               0
hip_pitch_offset:         13
period_time:              600
dsp_ratio:                0.1
step_forward_back_ratio:  0.28
foot_height:              0.04
swing_right_left:         0.020
swing_top_down:           0.005
pelvis_offset:            3.0
arm_swing_gain:           1.5
balance_hip_roll_gain:    0.5
balance_knee_gain:        0.3
balance_ankle_roll_gain:  1.0
balance_ankle_pitch_gain: 0.9
p_gain:                   32
i_gain:                   0
d_gain:                   0