head_pan:   # MX-28
   return_delay_time        : 1     # item name : value
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095

head_tilt:  # MX-28
   return_delay_time        : 1
   CW_angle_limit           : 0
   CCW_angle_limit          : 4095

r_sho_pitch :   # AX-12
   return_delay_time        : 1
   CW_angle_limit           : 200
   CCW_angle_limit          : 830

l_sho_pitch :   # AX-12
   return_delay_time        : 1
   CW_angle_limit           : 200
   CCW_angle_limit          : 830

r_sho_roll :   # AX-12
   return_delay_time        : 1
   CW_angle_limit           : 500
   CCW_angle_limit          : 1010

l_sho_roll :   # AX-12
   return_delay_time        : 1
   CW_angle_limit           : 500
   CCW_angle_limit          : 1010

r_el :   # AX-12
   return_delay_time        : 1
   CW_angle_limit           : 500
   CCW_angle_limit          : 830

l_el :   # AX-12
   return_delay_time        : 1
   CW_angle_limit           : 500
   CCW_angle_limit          : 830

r_hip_yaw :  # MX-64
   return_delay_time        : 1
   CW_angle_limit           : 1600
   CCW_angle_limit          : 2400

l_hip_yaw :  # MX-64
   return_delay_time        : 1
   CW_angle_limit           : 1600
   CCW_angle_limit          : 2400

r_hip_roll :  # MX-64
   return_delay_time        : 1
   CW_angle_limit           : 1500
   CCW_angle_limit          : 2500

l_hip_roll :  # MX-64
   return_delay_time        : 1
   CW_angle_limit           : 1500
   CCW_angle_limit          : 2500

r_hip_pitch :  # MX-64
   return_delay_time        : 1
   CW_angle_limit           : 1023
   CCW_angle_limit          : 3073

l_hip_pitch :  # MX-64
   return_delay_time        : 1
   CW_angle_limit           : 1023
   CCW_angle_limit          : 3073

r_knee :  # MX-64
   return_delay_time        : 1
   CW_angle_limit           : 2048
   CCW_angle_limit          : 2800

l_knee :  # MX-64
   return_delay_time        : 1
   CW_angle_limit           : 2048
   CCW_angle_limit          : 2800

r_ank_pitch :  # MX-64
   return_delay_time        : 1
   CW_angle_limit           : 1600
   CCW_angle_limit          : 2500

l_ank_pitch :  # MX-64
   return_delay_time        : 1
   CW_angle_limit           : 1600
   CCW_angle_limit          : 2500

r_ank_roll :  # MX-64
   return_delay_time        : 1
   CW_angle_limit           : 1600
   CCW_angle_limit          : 2500

l_ank_roll :  # MX-64
   return_delay_time        : 1
   CW_angle_limit           : 1600
   CCW_angle_limit          : 2500

waist:        # MX-64
   return_delay_time        : 1
   CW_angle_limit           : 1600
   CCW_angle_limit          : 2500
